echo "PWD: $PWD"
echo "APPCENTER_SOURCE_DIRECTORY: $APPCENTER_SOURCE_DIRECTORY"
echo "APPCENTER_ANDROID_VARIANT: $APPCENTER_ANDROID_VARIANT"
echo "APPCENTER_XCODE_PROJECT: $APPCENTER_XCODE_PROJECT"

if [ ! -z "$GOOGLE_SERVICES_JSON" ]; then
  echo $GOOGLE_SERVICES_JSON | base64 --decode > "$APPCENTER_SOURCE_DIRECTORY/android/app/google-services.json"
else
  echo "No GOOGLE_SERVICES_JSON in environment variables"
fi
