platform :ios, '9.0'

target 'Hekla' do

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'Interactable', :path => '../node_modules/react-native-interactable'
  pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-cookies', :path => '../node_modules/react-native-cookies/ios'
  pod 'ReactNativeSearchBar', :path => '../node_modules/react-native-search-bar'
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'


  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'ART',
    'RCTActionSheet',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'DevSupport',
  ]
end
