fastlane_version "2.69.2"

default_platform :ios

project_name = "Hekla"
scheme = project_name
path = "./#{project_name}.xcodeproj"

platform :ios do

  before_all do
  end

  desc "App Center Release"
  lane :appcenter_release do
    # Set build number to unique build id from app center
    increment_build_number(
      build_number: ENV["APPCENTER_BUILD_ID"],
      xcodeproj: path
    )
  end

  desc "Build"
  lane :build do
    xcodebuild(
      workspace: "./#{project_name}.xcworkspace",
      scheme: scheme,
      configuration: "Debug",
      build: true,
      destination: "generic/platform=iOS",
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      }
    )
  end

  desc "Build Release"
  lane :build_release do
    gym(
      scheme: scheme,
      workspace: "./#{project_name}.xcworkspace",
      output_directory: "ios/build",
      configuration: "Release",
      export_method: "app-store"
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end

end
